### LISTAR TODAS
GET http://localhost:3000/tarefas

### FILTRAR
GET http://localhost:3000/tarefas?concluido=false

### BUSCAR POR ID
GET http://localhost:3000/tarefas/1

### CRIAR
POST http://localhost:3000/tarefas
Content-Type: application/json

{
  "descricao": "Nova tarefa",
  "concluido": false
}

### ATUALIZAR
PATCH http://localhost:3000/tarefas/1
Content-Type: application/json

{
  "concluido": true
}

### DELETAR
DELETE http://localhost:3000/tarefas/1